#!/usr/bin/env node
// Regenerates js/data.js with a daily BTC/USD close series.
//
// Sources, tried in order:
//   1. CoinGecko market_chart API (primary, per spec)
//   2. Coin Metrics community daily CSV (online fallback, long history)
//   3. tools/btc-fallback.csv, a snapshot committed to this repo (offline-safe fallback)
//
// Any calendar day missing from the chosen source is forward-filled from the
// previous day's close, and the number of filled days is logged.
//
// Usage: node tools/fetch-data.mjs

import { writeFile, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "..", "js", "data.js");
const FALLBACK_CSV_PATH = path.join(__dirname, "btc-fallback.csv");

const COINGECKO_URL =
  "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=max&interval=daily";
const COINMETRICS_URL =
  "https://raw.githubusercontent.com/coinmetrics/data/master/csv/btc.csv";

const FETCH_TIMEOUT_MS = 20_000;

async function fetchWithTimeout(url, opts = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    return await fetch(url, { ...opts, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

function toISODate(ms) {
  return new Date(ms).toISOString().slice(0, 10);
}

// Returns a Map<"YYYY-MM-DD", number> or throws.
async function fetchCoinGecko() {
  const res = await fetchWithTimeout(COINGECKO_URL);
  if (!res.ok) throw new Error(`CoinGecko HTTP ${res.status}`);
  const json = await res.json();
  const prices = json?.prices;
  if (!Array.isArray(prices) || prices.length === 0) {
    throw new Error("CoinGecko response missing prices[]");
  }
  const byDate = new Map();
  for (const [ms, price] of prices) {
    byDate.set(toISODate(ms), price);
  }
  return byDate;
}

// Returns a Map<"YYYY-MM-DD", number> or throws.
async function fetchCoinMetrics() {
  const res = await fetchWithTimeout(COINMETRICS_URL);
  if (!res.ok) throw new Error(`Coin Metrics HTTP ${res.status}`);
  const text = await res.text();
  return parseDateCloseCsv(text, "time", "PriceUSD");
}

async function readFallbackCsv() {
  const text = await readFile(FALLBACK_CSV_PATH, "utf8");
  return parseDateCloseCsv(text, "date", "close");
}

function parseDateCloseCsv(text, dateCol, closeCol) {
  const lines = text.trim().split("\n");
  const header = lines[0].split(",");
  const dateIdx = header.indexOf(dateCol);
  const closeIdx = header.indexOf(closeCol);
  if (dateIdx === -1 || closeIdx === -1) {
    throw new Error(`CSV missing expected columns ${dateCol}/${closeCol}`);
  }
  const byDate = new Map();
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split(",");
    const dateStr = cols[dateIdx];
    const closeStr = cols[closeIdx];
    if (!dateStr || !closeStr) continue;
    const close = Number(closeStr);
    if (!Number.isFinite(close)) continue;
    byDate.set(dateStr.slice(0, 10), close);
  }
  return byDate;
}

function daysBetween(a, b) {
  const msPerDay = 86_400_000;
  return Math.round((b.getTime() - a.getTime()) / msPerDay);
}

function parseISO(dateStr) {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

// Builds a contiguous daily closes[] array from a sparse Map, forward-filling gaps.
function buildContiguousSeries(byDate) {
  const dates = [...byDate.keys()].sort();
  const startDate = dates[0];
  const endDate = dates[dates.length - 1];
  const start = parseISO(startDate);
  const end = parseISO(endDate);
  const totalDays = daysBetween(start, end) + 1;

  const closes = new Array(totalDays);
  let lastClose = byDate.get(startDate);
  let filled = 0;
  for (let i = 0; i < totalDays; i++) {
    const cur = new Date(start.getTime() + i * 86_400_000);
    const key = cur.toISOString().slice(0, 10);
    if (byDate.has(key)) {
      lastClose = byDate.get(key);
    } else {
      filled++;
    }
    closes[i] = lastClose;
  }
  return { startDate, endDate, closes, filled };
}

async function main() {
  let byDate;
  let sourceName;

  try {
    byDate = await fetchCoinGecko();
    sourceName = "CoinGecko";
  } catch (err) {
    console.warn(`CoinGecko fetch failed (${err.message}), trying Coin Metrics...`);
    try {
      byDate = await fetchCoinMetrics();
      sourceName = "Coin Metrics";
    } catch (err2) {
      console.warn(`Coin Metrics fetch failed (${err2.message}), using committed fallback CSV...`);
      byDate = await readFallbackCsv();
      sourceName = "committed fallback CSV";
    }
  }

  const { startDate, endDate, closes, filled } = buildContiguousSeries(byDate);

  const js =
    `// Generated by tools/fetch-data.mjs from ${sourceName} on ${new Date().toISOString()}\n` +
    `// Do not hand-edit. Re-run \`node tools/fetch-data.mjs\` to refresh.\n` +
    `window.BTC_DATA = {\n` +
    `  startDate: ${JSON.stringify(startDate)},\n` +
    `  source: ${JSON.stringify(sourceName)},\n` +
    `  fillCount: ${filled}, // calendar days forward-filled from the previous close at fetch time\n` +
    `  closes: [${closes.map((c) => roundClose(c)).join(",")}]\n` +
    `};\n`;

  await writeFile(OUT_PATH, js, "utf8");

  console.log(`Source: ${sourceName}`);
  console.log(`Range: ${startDate} .. ${endDate} (${closes.length} days, ${filled} forward-filled)`);
  console.log(`Last close: ${closes[closes.length - 1]}`);
  console.log(`Wrote ${OUT_PATH}`);
}

function roundClose(x) {
  // Keep the file compact; price data does not need more than 6 significant fractional digits.
  return Math.round(x * 1e6) / 1e6;
}

main().catch((err) => {
  console.error("fetch-data failed:", err);
  process.exit(1);
});
