#!/usr/bin/env node
// Regenerates js/data.js with a daily BTC/USD close series from the Coin
// Metrics v4 community API. Single source, no fallbacks: if the API call
// fails, or the returned series has a gap or is stale, this exits(1) rather
// than writing anything. Never substitutes or generates data.
//
// Usage: node tools/fetch-data.mjs

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "..", "js", "data.js");

const COINMETRICS_URL =
  "https://community-api.coinmetrics.io/v4/timeseries/asset-metrics?assets=btc&metrics=PriceUSD&frequency=1d&page_size=10000";

const FETCH_TIMEOUT_MS = 20_000;
const MAX_STALE_DAYS = 3;

async function fetchWithTimeout(url, opts = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    return await fetch(url, { ...opts, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

function daysBetween(a, b) {
  const msPerDay = 86_400_000;
  return Math.round((b.getTime() - a.getTime()) / msPerDay);
}

function parseISO(dateStr) {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

function roundClose(x) {
  // Keep the file compact; price data does not need more than 6 significant fractional digits.
  return Math.round(x * 1e6) / 1e6;
}

// Fetches the full asset-metrics series, following next_page_url until it's
// absent. Returns Map<"YYYY-MM-DD", number>. Throws (with HTTP status + body)
// on any non-OK response — the caller exits(1) rather than retrying or
// substituting another source.
async function fetchCoinMetrics() {
  const byDate = new Map();
  let url = COINMETRICS_URL;

  while (url) {
    const res = await fetchWithTimeout(url);
    if (!res.ok) {
      const body = await res.text().catch(() => "<failed to read response body>");
      throw new Error(`Coin Metrics HTTP ${res.status}\n${body}`);
    }
    const json = await res.json();
    const rows = json?.data;
    if (!Array.isArray(rows)) {
      throw new Error(`Coin Metrics response missing data[]: ${JSON.stringify(json).slice(0, 500)}`);
    }
    for (const row of rows) {
      const price = Number(row.PriceUSD);
      if (!row.time || !Number.isFinite(price)) continue;
      byDate.set(String(row.time).slice(0, 10), price);
    }
    url = json.next_page_url || null;
  }

  if (byDate.size === 0) {
    throw new Error("Coin Metrics returned zero rows");
  }
  return byDate;
}

// Hard guard: every consecutive pair of dates must be exactly 1 calendar day
// apart. A gap here means the source is missing days — fail loudly rather
// than forward-filling a synthesized price over the hole.
function assertContiguous(dates) {
  for (let i = 1; i < dates.length; i++) {
    const gap = daysBetween(parseISO(dates[i - 1]), parseISO(dates[i]));
    if (gap !== 1) {
      console.error(
        `Gap in Coin Metrics series: ${dates[i - 1]} -> ${dates[i]} is ${gap} day(s) apart, expected exactly 1.`
      );
      process.exit(1);
    }
  }
}

// Hard guard: the series must not be stale. This is what actually catches a
// truncated/incomplete fetch — a silently-short series still "succeeds" as
// an HTTP request.
function assertFresh(lastDate) {
  const now = new Date();
  const today = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const staleDays = daysBetween(parseISO(lastDate), today);
  if (staleDays > MAX_STALE_DAYS) {
    console.error(
      `Coin Metrics series is stale: last date ${lastDate} is ${staleDays} day(s) before today ` +
        `(${today.toISOString().slice(0, 10)}). Expected <= ${MAX_STALE_DAYS}.`
    );
    process.exit(1);
  }
}

async function main() {
  let byDate;
  try {
    byDate = await fetchCoinMetrics();
  } catch (err) {
    console.error(`Coin Metrics fetch failed: ${err.message}`);
    process.exit(1);
  }

  const dates = [...byDate.keys()].sort();
  assertContiguous(dates);
  assertFresh(dates[dates.length - 1]);

  const startDate = dates[0];
  const endDate = dates[dates.length - 1];
  const closes = dates.map((d) => roundClose(byDate.get(d)));

  const js =
    `// Generated by tools/fetch-data.mjs from Coin Metrics on ${new Date().toISOString()}\n` +
    `// Do not hand-edit. Re-run \`node tools/fetch-data.mjs\` to refresh.\n` +
    `window.BTC_DATA = {\n` +
    `  startDate: ${JSON.stringify(startDate)},\n` +
    `  source: "Coin Metrics",\n` +
    `  fillCount: 0, // guaranteed 0: assertContiguous above exits(1) rather than allowing a gap to reach here\n` +
    `  closes: [${closes.join(",")}]\n` +
    `};\n`;

  await writeFile(OUT_PATH, js, "utf8");

  console.log(`First date: ${startDate}`);
  console.log(`Last date: ${endDate}`);
  console.log(`Last close: ${closes[closes.length - 1]}`);
  console.log(`Rows: ${closes.length}`);
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error("fetch-data failed:", err);
  process.exit(1);
});
